yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "node-modules"

logFilters:
  # Consider incorrect dependencies as errors instead of warnings
  - code: YN0002
    level: error
  # Consider incorrect versions of peerDependencies as warnings
  # Hopefully, we will be able to change this, but there are
  # no way for us to fix those warnings.
  - code: YN0060
    level: "warning"

packageExtensions:
  "@chakra-ui/accordion@1.3.1":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@1.1.12":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@1.2.5":
    peerDependencies:
      framer-motion: "*"
  eslint-config-airbnb-typescript@12.3.1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
  "@storybook/core@*":
    peerDependencies:
      webpack: "*"
  "react-dev-utils@*":
    peerDependencies:
      webpack: "*"
      typescript: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      typescript: "*"
  "graphql-config@3.3.0":
    peerDependencies:
      typescript: "*"
  "@graphql-codegen/cli@1.21.4":
    peerDependencies:
      typescript: "*"
