version: "3.5"
services:
  pgadmin:
    image: dpage/pgadmin4:4.30
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
