version: "3.5"
services:
  db:
    image: postgres:12.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_home:/var/lib/postgresql/data
  db_test:
    image: postgres:12.6
    ports:
      - "5435:5434"
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    command: -p 5434
    volumes:
      - db_home_test:/var/lib/postgresql/data

volumes:
  db_home:
    external: false
  db_home_test:
    external: false
