on:
  schedule:
    - cron:  '0 0 * * *' # at midnight (utc) every day
jobs:
  build:
    name: Run AskGit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout AskGit repo
      uses: actions/checkout@v2
      with:
        repository: askgitdev/askgit
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install libgit2
      run: sudo ./scripts/install_libgit2.sh

    - name: Build AskGit
      run: |
        make
        cp .build/askgit /usr/local/bin/askgit

    - name: Sync tables
      run: |
        export PGSYNC=1
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export GITHUB_PER_PAGE=50
        export POSTGRES_CONNECTION=${{ secrets.POSTGRES_CONNECTION_ASKGIT }}
        askgit pgsync pull_requests "SELECT * FROM github_repo_prs('labelflow/labelflow')"
        askgit pgsync issues "SELECT * FROM github_repo_issues('labelflow/labelflow')"
        askgit pgsync repos "SELECT * FROM github_org_repos('labelflow')"
        askgit pgsync commit_stats "SELECT * FROM commits('https://github.com/labelflow/labelflow'), stats('https://github.com/labelflow/labelflow', commits.hash)"
        askgit pgsync stargazers "SELECT * FROM github_stargazers('labelflow/labelflow')"
