name: Auto create PR
on:
  push:
    branches-ignore:
      - main
jobs:
  auto-pull-request:
    name: Pull Request Action
    runs-on: ubuntu-20.04
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: ""
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_DRAFT: "true"