name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Fetch/Save yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn install --immutable
      - name: Ensure node_modules are up to date in the cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('/yarn.lock') }}

  lint:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Fetch node_modules from cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('/yarn.lock') }}
      - name: lint project code
        run: yarn lint

  test:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Fetch node_modules from cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('/yarn.lock') }}
      - name: run tests
        run: yarn test

  e2e:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Fetch node_modules from cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('/yarn.lock') }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn --immutable
          # install: false
          build: yarn build:web-app
          start: yarn start:web-app
          wait-on: "http://localhost:3000"

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Deploy webapp on Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_WEBAPP}} #Required 
          working-directory: typescript/web-app
